# Generated by Django 3.1.5 on 2021-01-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(blank=True, max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_num', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('job', models.ManyToManyField(blank=True, to='employee.AvailableJobs')),
            ],
        ),
    ]
